テストを追加
makiichikawa/fjord-books_app pull request #8
Opened 2021-03-08 09:28 UTC by MakiIchikawa

表記のコードを追加しましたので、確認のほどよろしくお願いいたします。

2021-03-12 05:12 UTC, komagata requested changes
テストとして問題ないですが、factory_botがテストの中で一度も使われてないかもです。

factory_bot自体を削除しちゃうか、テスト中で自分でデータをcreateせずにfactory_botで作ったデータを使うようにすると良いかもです〜

2021-03-12 05:12 UTC, komagata commented on .vscode/settings.json
> +}
ファイルの末尾に改行がないようです。
エディタの設定で自動で入るようにできますので試してみてください〜

2021-03-17 01:34 UTC, MakiIchikawa commented on .vscode/settings.json
> +}
申し訳ありません。。😱

不要なファイルを削除しました。

2021-03-17 01:38 UTC, MakiIchikawa commented on .vscode/settings.json
> +}
モデルテストについてfactory_botが作ったデータを使用するように変更しました。

システムテストについては`FactoryBot.create`を使用しているので問題ない認識でおります。

2021-03-17 01:50 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-05-06 07:05 UTC, merged